version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.4

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run linters
      - run: yarn lint-js
      - run: yarn lint-ts
      # run tests!
      - run: yarn test --verbose --coverage=true --forceExit --detectOpenHandles
